// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/goal-tasks/AlwaysVisibleChecklist.tsx": () => import("../components/mockups/goal-tasks/AlwaysVisibleChecklist.tsx"),
  "./components/mockups/goal-tasks/ProgressRoadmap.tsx": () => import("../components/mockups/goal-tasks/ProgressRoadmap.tsx"),
  "./components/mockups/goal-tasks/StepFirstGrid.tsx": () => import("../components/mockups/goal-tasks/StepFirstGrid.tsx"),
  "./components/mockups/goal-tasks/StepHistoryCards.tsx": () => import("../components/mockups/goal-tasks/StepHistoryCards.tsx"),
  "./components/mockups/multi-assign/BulkUploadHub.tsx": () => import("../components/mockups/multi-assign/BulkUploadHub.tsx"),
  "./components/mockups/multi-assign/BulkUploadTab.tsx": () => import("../components/mockups/multi-assign/BulkUploadTab.tsx"),
  "./components/mockups/multi-assign/EmpMgmtHeaderBtn.tsx": () => import("../components/mockups/multi-assign/EmpMgmtHeaderBtn.tsx"),
  "./components/mockups/multi-assign/EmpMgmtToolbar.tsx": () => import("../components/mockups/multi-assign/EmpMgmtToolbar.tsx"),
  "./components/mockups/step-timer/GuardedReset.tsx": () => import("../components/mockups/step-timer/GuardedReset.tsx"),
  "./components/mockups/step-timer/HoldToReset.tsx": () => import("../components/mockups/step-timer/HoldToReset.tsx"),
  "./components/mockups/step-timer/TapCard.tsx": () => import("../components/mockups/step-timer/TapCard.tsx"),
  "./components/mockups/video-display/InlinePlayer.tsx": () => import("../components/mockups/video-display/InlinePlayer.tsx")
};
